---
driver:
  name: docker
  hostname: octavia.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: octavia
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
  state_top:
    base:
      "*":
        - linux.system
        - octavia
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - octavia
  pillars-from-files:
    linux_repo_openstack.sls: tests/pillar/repo_openstack_<%= ENV['OS_VERSION'] || 'ocata' %>.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:
  - name: api_single
    provisioner:
      pillars-from-files:
        octavia.sls: tests/pillar/api_single.sls
      pillars:
        release.sls:
          octavia:
            api:
              version: <%= ENV['OS_VERSION'] || 'ocata' %>

  - name: api_cluster
    provisioner:
      pillars-from-files:
        octavia.sls: tests/pillar/api_cluster.sls
      pillars:
        release.sls:
          octavia:
            api:
              version: <%= ENV['OS_VERSION'] || 'ocata' %>

  - name: manager_single
    provisioner:
      pillars-from-files:
        octavia.sls: tests/pillar/manager_single.sls
      pillars:
        release.sls:
          octavia:
            manager:
              version: <%= ENV['OS_VERSION'] || 'ocata' %>

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
