---
driver:
  name: docker
  hostname: octavia.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: octavia
  grains:
    noservices: True
  dependencies:
    - name: neutron
      repo: git
      source: https://github.com/salt-formulas/salt-formula-neutron
    - name: nova
      repo: git
      source: https://github.com/salt-formulas/salt-formula-nova
  state_top:
    base:
      "*":
        - octavia
  pillars:
    top.sls:
      base:
        "*":
          - octavia

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:
  - name: single
    provisioner:
      pillars-from-files:
        octavia.sls: tests/pillar/single.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
